string type
sensor_msgs/NavSatFix[] waypoint
float64 radius
float64 maxVel
float64 idleVel

std_msgs/Float64MultiArray yaw
std_msgs/Float64MultiArray gimbalPitch 
std_msgs/Float64MultiArray speed
int8 yawMode
int8 traceMode
int8 gimbalPitchMode
int8 finishAction
#actions
std_msgs/Float64MultiArray commandList
std_msgs/Float64MultiArray commandParameter 
---
bool success
